export const ADD_VP_CHIP = 'ADD_VP_CHIP';
export const SUBTRACT_VP_CHIP = 'SUBTRACT_VP_CHIP';
export const TOGGLE_BUILDING_BUILT = 'TOGGLE_BUILDING_BUILT';
export const TOGGLE_BUILDING_HAS_WORKER = 'TOGGLE_BUILDING_HAS_WORKER';
export const SET_ISLAND_SPACES_OCCUPIED = 'SET_ISLAND_SPACES_OCCUPIED';
export const SET_TOTAL_COLONISTS = 'SET_TOTAL_COLONISTS';
