const buildingTypes = {
  PRODUCTION_SMALL: 'PRODUCTION_SMALL',
  PRODUCTION_LARGE: 'PRODUCTION_LARGE',
  VIOLET: 'VIOLET',
}

const initialState = {
  vpChips: 0,
  buildings: [
    {
      name: "Small Indigo Plant",
      type: buildingTypes.PRODUCTION_SMALL,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Small Sugar Mill",
      type: buildingTypes.PRODUCTION_SMALL,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Small Market",
      type: buildingTypes.VIOLET,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Hacienda",
      type: buildingTypes.VIOLET,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Construction Hut",
      type: buildingTypes.VIOLET,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Small Warehouse",
      type: buildingTypes.VIOLET,
      points: 1,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Indigo Plant",
      type: buildingTypes.PRODUCTION_LARGE,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Sugar Mill",
      type: buildingTypes.PRODUCTION_LARGE,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Hospice",
      type: buildingTypes.VIOLET,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Office",
      type: buildingTypes.VIOLET,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Large Market",
      type: buildingTypes.VIOLET,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Large Warehouse",
      type: buildingTypes.VIOLET,
      points: 2,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Tobacco Storage",
      type: buildingTypes.PRODUCTION_LARGE,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Coffee Roaster",
      type: buildingTypes.PRODUCTION_LARGE,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Factory",
      type: buildingTypes.VIOLET,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "University",
      type: buildingTypes.VIOLET,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Harbor",
      type: buildingTypes.VIOLET,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Wharf",
      type: buildingTypes.VIOLET,
      points: 3,
      isBuilt: false,
      hasWorker: null,
      bonusInput: null,
    },
    {
      name: "Guild Hall",
      type: buildingTypes.VIOLET,
      points: 4,
      isBuilt: false,
      hasWorker: false,
      bonusInput: null,
    },
    {
      name: "Customs House",
      type: buildingTypes.VIOLET,
      points: 4,
      isBuilt: false,
      hasWorker: false,
      bonusInput: null,
    },
    {
      name: "Residence",
      type: buildingTypes.VIOLET,
      points: 4,
      isBuilt: false,
      hasWorker: false,
      bonusInput: {
        inputId: "islandSpaces",
        value: "",
        labelText: "Total occupied island spaces",
        inputPlaceholder: "Island spaces"
      },
    },
    {
      name: "City Hall",
      type: buildingTypes.VIOLET,
      points: 4,
      isBuilt: false,
      hasWorker: false,
      bonusInput: null,
    },
    {
      name: "Fortress",
      type: buildingTypes.VIOLET,
      points: 4,
      isBuilt: false,
      hasWorker: false,
      bonusInput: {
        inputId: "totalWorkers",
        value: "",
        labelText: "Total number of workers",
        inputPlaceholder: "Total workers"
      },
    }
  ]
}

export default initialState;
